# Generated by Django 5.0.6 on 2024-07-09 20:20

import django.db.models.deletion
import pgvector.django
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_postgres_vector_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangChainPgCollection',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, null=True)),
                ('cmetadata', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'langchain_pg_collection',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LangchainPgEmbedding',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('embedding', pgvector.django.VectorField(dimensions=768)),
                ('document', models.TextField(blank=True, null=True)),
                ('cmetadata', models.JSONField()),
                ('custom_id', models.CharField(blank=True, null=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_core.langchainpgcollection')),
            ],
            options={
                'db_table': 'langchain_pg_embedding',
            },
        ),
    ]
